/**
 * Ground-truth BehaviorTree.cpp v4 XML fixtures.
 *
 * These strings represent valid BT XML that follows the BehaviorTree.cpp v4
 * specification. They are used as reference data for serializer tests.
 *
 * If you need higher-fidelity examples you can replace or add fixtures
 * generated by Groot2 and paste them here as template literals.
 */

/** Minimal single-tree: root -> Sequence -> two actions */
export const MINIMAL_TREE_XML = `<?xml version="1.0"?>
<root BTCPP_format="4" main_tree_to_execute="MainTree">
  <!-- Generated by BTstudio -->

  <BehaviorTree ID="MainTree">
    <Sequence>
      <PrintMessage message="Hello"/>
      <Delay delay_msec="1000"/>
    </Sequence>
  </BehaviorTree>
</root>`;

/** Tree with a named node instance and variable references */
export const TREE_WITH_VARIABLES_XML = `<?xml version="1.0"?>
<root BTCPP_format="4" main_tree_to_execute="VarTree">
  <!-- Generated by BTstudio -->

  <BehaviorTree ID="VarTree">
    <Sequence>
      <SetBlackboard output_key="counter" value="0"/>
      <PrintMessage name="greet" message="{counter}"/>
    </Sequence>
  </BehaviorTree>
</root>`;

/** Multi-tree file with a main tree and one embedded subtree */
export const MULTI_TREE_XML = `<?xml version="1.0"?>
<root BTCPP_format="4" main_tree_to_execute="NavigationTree">
  <!-- Generated by BTstudio -->

  <BehaviorTree ID="NavigationTree">
    <Sequence>
      <SubTree ID="CheckBattery" threshold="{min_battery}"/>
      <PrintMessage message="Navigating"/>
    </Sequence>
  </BehaviorTree>

  <!-- Checks whether battery level is sufficient -->
  <BehaviorTree ID="CheckBattery">
    <Sequence>
      <CheckVariable variable="battery" expected_value="100"/>
    </Sequence>
  </BehaviorTree>

  <!-- Subtree port definitions -->
  <TreeNodesModel>
    <SubTree ID="CheckBattery">
      <input_port name="threshold" type="number" required="true">Minimum battery level</input_port>
      <output_port name="status" type="string">Battery status string</output_port>
    </SubTree>
  </TreeNodesModel>

</root>`;

/** Subtree library file (no main_tree_to_execute) */
export const SUBTREE_LIBRARY_XML = `<?xml version="1.0"?>
<root BTCPP_format="4">
  <!-- BTstudio Subtree Library -->

  <!-- Checks whether battery level is sufficient -->
  <BehaviorTree ID="CheckBattery">
    <Sequence>
      <CheckVariable variable="battery" expected_value="100"/>
    </Sequence>
  </BehaviorTree>

  <!-- Subtree port definitions -->
  <TreeNodesModel>
    <SubTree ID="CheckBattery">
      <input_port name="threshold" type="number" required="true">Minimum battery level</input_port>
      <output_port name="status" type="string">Battery status string</output_port>
    </SubTree>
  </TreeNodesModel>

</root>`;

/** Tree with decorator nodes */
export const DECORATOR_TREE_XML = `<?xml version="1.0"?>
<root BTCPP_format="4" main_tree_to_execute="DecoratorTree">
  <!-- Generated by BTstudio -->

  <BehaviorTree ID="DecoratorTree">
    <Inverter>
      <Retry num_attempts="3">
        <PrintMessage message="trying"/>
      </Retry>
    </Inverter>
  </BehaviorTree>
</root>`;

/** Empty tree with just a root (no children) */
export const EMPTY_TREE_XML = `<?xml version="1.0"?>
<root BTCPP_format="4" main_tree_to_execute="EmptyTree">
  <!-- Generated by BTstudio -->

  <BehaviorTree ID="EmptyTree">
  </BehaviorTree>
</root>`;

/** Tree with DeclareVariable (SetBlackboard that is first assignment) */
export const DECLARE_VARIABLE_TREE_XML = `<?xml version="1.0"?>
<root BTCPP_format="4" main_tree_to_execute="VarDeclTree">
  <!-- Generated by BTstudio -->

  <BehaviorTree ID="VarDeclTree">
    <Sequence>
      <SetBlackboard output_key="my_var" value="42"/>
      <SetBlackboard output_key="my_var" value="99"/>
    </Sequence>
  </BehaviorTree>
</root>`;

/**
 * Tree with multiple control node children to test ordering.
 * Fallback has three action children that should maintain left-to-right order.
 */
export const CONTROL_ORDERING_XML = `<?xml version="1.0"?>
<root BTCPP_format="4" main_tree_to_execute="OrderTree">
  <!-- Generated by BTstudio -->

  <BehaviorTree ID="OrderTree">
    <Fallback>
      <PrintMessage message="A"/>
      <PrintMessage message="B"/>
      <PrintMessage message="C"/>
    </Fallback>
  </BehaviorTree>
</root>`;

/** Tree with special characters that need XML escaping */
export const SPECIAL_CHARS_XML = `<?xml version="1.0"?>
<root BTCPP_format="4" main_tree_to_execute="EscapeTree">
  <!-- Generated by BTstudio -->

  <BehaviorTree ID="EscapeTree">
    <PrintMessage message="a &amp; b &lt; c"/>
  </BehaviorTree>
</root>`;

/** Subtree library with custom subtree colors stored as BTstudio metadata comments */
export const SUBTREE_LIBRARY_WITH_COLORS_XML = `<?xml version="1.0"?>
<root BTCPP_format="4">
  <!-- BTstudio Subtree Library -->

  <!-- Checks whether battery level is sufficient -->
  <!-- BTstudio:color=#FF5722 -->
  <BehaviorTree ID="CheckBattery">
    <Sequence>
      <CheckVariable variable="battery" expected_value="100"/>
    </Sequence>
  </BehaviorTree>

  <!-- Runs a navigation routine -->
  <BehaviorTree ID="Navigate">
    <Sequence>
      <PrintMessage message="navigating"/>
    </Sequence>
  </BehaviorTree>

  <!-- Subtree port definitions -->
  <TreeNodesModel>
    <SubTree ID="CheckBattery">
      <input_port name="threshold" type="number" required="true">Minimum battery level</input_port>
    </SubTree>
  </TreeNodesModel>

</root>`;

/** Multi-tree file with a colored subtree */
export const MULTI_TREE_WITH_COLOR_XML = `<?xml version="1.0"?>
<root BTCPP_format="4" main_tree_to_execute="MainTree">
  <!-- Generated by BTstudio -->

  <BehaviorTree ID="MainTree">
    <Sequence>
      <SubTree ID="CheckBattery"/>
    </Sequence>
  </BehaviorTree>

  <!-- Battery check routine -->
  <!-- BTstudio:color=#E91E63 -->
  <BehaviorTree ID="CheckBattery">
    <Sequence>
      <CheckVariable variable="battery" expected_value="100"/>
    </Sequence>
  </BehaviorTree>

</root>`;
