/**
 * XML serialization / deserialization for BehaviorTree.cpp v4 format.
 *
 * Converts between the editor's internal ReactFlow representation
 * (nodes + edges + variables) and the BT XML consumed by BehaviorTree.CPP.
 *
 * Public surface:
 *   Export:  exportToXML, exportMultiTreeToXML, exportSubtreeLibraryToXML
 *   Import:  importFromXML, importMultiTreeFromXML, importSubtreeLibraryFromXML
 *   Helpers: getReferencedSubtreeIds, updateSubtreeInXML
 *   Types:   TreeData, MultiTreeParseResult, MAIN_TREE_ID
 *
 * When editing this file, also update the corresponding tests in
 * src/test/xmlSerializer.test.ts.
 */

import { AppNode, AppEdge, NodeField, SubTreePort, Variable } from '../types';
import { getCategoryColor, inferCategoryFromType } from '../data/nodeLibrary';

// ---------------------------------------------------------------------------
// Serialization options
// ---------------------------------------------------------------------------

interface SerializationOptions {
  /** Pretty-print the output (default: true). */
  formatOutput?: boolean;
  /** Include generated-by comments (default: true). */
  includeComments?: boolean;
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** A single BehaviorTree stored in a file. */
export interface TreeData {
  /** BehaviorTree ID attribute (e.g. "NavigationTree"). */
  id: string;
  nodes: AppNode[];
  edges: AppEdge[];
  variables: Variable[];
  /** Optional human-readable description (stored as an XML comment). */
  description?: string;
  /** Input/output ports for subtrees. */
  ports?: SubTreePort[];
  /** Optional custom color for subtree display (stored as an XML comment). */
  color?: string;
}

/** Sentinel ID that BehaviorTree.cpp uses for its main tree attribute. */
export const MAIN_TREE_ID = 'main_tree_to_execute';

/** Result of parsing a multi-tree XML file. */
export interface MultiTreeParseResult {
  mainTree: TreeData;
  subtrees: Map<string, TreeData>;
  /** Preserves the document order of trees in the file. */
  treeOrder: string[];
}

// ═══════════════════════════════════════════════════════════════════════════
// EXPORT (editor -> XML)
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Export a single tree to BehaviorTree.cpp v4 XML.
 */
export function exportToXML(
  nodes: AppNode[],
  edges: AppEdge[],
  variables: Variable[],
  treeId: string = 'MainTree',
  options: SerializationOptions = {},
): string {
  const { formatOutput = true, includeComments = true } = options;

  const treeStructure = buildTreeStructure(nodes, edges);

  let xml = '<?xml version="1.0"?>\n';
  xml += `<root BTCPP_format="4" main_tree_to_execute="${escapeXML(treeId)}">\n`;

  if (includeComments) {
    xml += '  <!-- Generated by BTstudio -->\n\n';
  }

  xml += `  <BehaviorTree ID="${escapeXML(treeId)}">\n`;
  xml += serializeNodeRecursive(treeStructure.root, nodes, edges, variables, 2);
  xml += '  </BehaviorTree>\n';
  xml += '</root>';

  return formatOutput ? xml : xml.replace(/\n\s*/g, '');
}

/**
 * Export multiple trees (main + subtrees) to a single XML file.
 *
 * Used when saving a workspace file that embeds its referenced subtrees.
 */
export function exportMultiTreeToXML(
  mainTree: TreeData,
  subtrees: Map<string, TreeData>,
  options: SerializationOptions = {},
): string {
  const { formatOutput = true, includeComments = true } = options;

  let xml = '<?xml version="1.0"?>\n';
  xml += `<root BTCPP_format="4" main_tree_to_execute="${escapeXML(mainTree.id)}">\n`;

  if (includeComments) {
    xml += '  <!-- Generated by BTstudio -->\n\n';
  }

  // Main tree first
  xml += serializeBehaviorTree(mainTree);
  xml += '\n';

  // Then subtrees in insertion order
  subtrees.forEach((subtreeData) => {
    xml += serializeBehaviorTree(subtreeData);
    xml += '\n';
  });

  // Port definitions
  xml += serializeTreeNodesModel(subtrees);
  xml += '</root>';

  return formatOutput ? xml : xml.replace(/\n\s*/g, '');
}

/**
 * Export the workspace subtree library to XML.
 *
 * The library file has no `main_tree_to_execute` attribute because it
 * only contains reusable subtree definitions.
 */
export function exportSubtreeLibraryToXML(
  subtrees: Map<string, TreeData>,
  options: SerializationOptions = {},
): string {
  const { formatOutput = true, includeComments = true } = options;

  let xml = '<?xml version="1.0"?>\n';
  xml += '<root BTCPP_format="4">\n';

  if (includeComments) {
    xml += '  <!-- BTstudio Subtree Library -->\n\n';
  }

  subtrees.forEach((subtreeData) => {
    xml += serializeBehaviorTree(subtreeData);
    xml += '\n';
  });

  xml += serializeTreeNodesModel(subtrees);
  xml += '</root>';

  return formatOutput ? xml : xml.replace(/\n\s*/g, '');
}

// ═══════════════════════════════════════════════════════════════════════════
// IMPORT (XML -> editor)
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Import a single-tree BehaviorTree.cpp XML string (convenience wrapper).
 *
 * For files that contain multiple trees, use `importMultiTreeFromXML`.
 */
export function importFromXML(xmlString: string): {
  nodes: AppNode[];
  edges: AppEdge[];
  variables: Variable[];
} {
  const result = importMultiTreeFromXML(xmlString);
  return {
    nodes: result.mainTree.nodes,
    edges: result.mainTree.edges,
    variables: result.mainTree.variables,
  };
}

/**
 * Import a multi-tree BehaviorTree.cpp XML file.
 *
 * The main tree is identified by:
 *   1. Matching `main_tree_to_execute` attribute.
 *   2. First `<BehaviorTree>` element if the attribute is absent.
 *   3. Fallback: tree with ID equal to `MAIN_TREE_ID`.
 */
export function importMultiTreeFromXML(xmlString: string): MultiTreeParseResult {
  const root = parseAndValidateRoot(xmlString);
  const mainTreeId = root.getAttribute('main_tree_to_execute');
  const behaviorTrees = root.querySelectorAll('BehaviorTree');

  if (behaviorTrees.length === 0) {
    throw new Error('Invalid BehaviorTree XML: missing BehaviorTree element');
  }

  const descriptionMap = buildDescriptionMap(root);
  const colorMap = buildColorMap(root);
  const subtrees = new Map<string, TreeData>();
  const treeOrder: string[] = [];
  let mainTree: TreeData | null = null;

  behaviorTrees.forEach((btElement, index) => {
    const treeId = btElement.getAttribute('ID') || `Tree_${index}`;
    const description = descriptionMap.get(treeId) || btElement.getAttribute('description') || undefined;
    const color = colorMap.get(treeId) || undefined;
    treeOrder.push(treeId);

    const isMainTree =
      (mainTreeId && treeId === mainTreeId) ||
      (!mainTreeId && index === 0) ||
      treeId === MAIN_TREE_ID;

    const treeData = parseBehaviorTreeElement(btElement, treeId, description, color);

    if (isMainTree && !mainTree) {
      mainTree = treeData;
    } else {
      subtrees.set(treeId, treeData);
    }
  });

  if (!mainTree) {
    throw new Error('Failed to parse main tree');
  }

  // Attach port definitions from <TreeNodesModel>
  attachPortDefinitions(root, subtrees);

  // Annotate SubTree reference nodes' fields with portDirection from port defs
  const portDefs = parseTreeNodesModel(root);
  const allTrees = [mainTree!, ...Array.from(subtrees.values())];
  annotateSubTreeNodeFields(allTrees, portDefs, subtrees);

  return { mainTree, subtrees, treeOrder };
}

/**
 * Import a subtree library XML file.
 *
 * Returns a map from subtree ID to its TreeData.
 * Returns an empty map for invalid / empty library files.
 */
export function importSubtreeLibraryFromXML(xmlString: string): Map<string, TreeData> {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(xmlString, 'text/xml');

  if (xmlDoc.querySelector('parsererror')) {
    throw new Error('Invalid XML: ' + xmlDoc.querySelector('parsererror')!.textContent);
  }

  const root = xmlDoc.querySelector('root');
  if (!root) return new Map();

  const descriptionMap = buildDescriptionMap(root);
  const colorMap = buildColorMap(root);
  const behaviorTrees = root.querySelectorAll('BehaviorTree');
  const subtrees = new Map<string, TreeData>();

  behaviorTrees.forEach((btElement, index) => {
    const treeId = btElement.getAttribute('ID') || `SubTree_${index}`;
    const description = descriptionMap.get(treeId) || btElement.getAttribute('description') || undefined;
    const color = colorMap.get(treeId) || undefined;
    const treeData = parseBehaviorTreeElement(btElement, treeId, description, color);
    subtrees.set(treeId, treeData);
  });

  attachPortDefinitions(root, subtrees);

  // Annotate SubTree reference nodes' fields with portDirection from port defs
  const portDefs = parseTreeNodesModel(root);
  const allTrees = Array.from(subtrees.values());
  annotateSubTreeNodeFields(allTrees, portDefs, subtrees);

  return subtrees;
}

// ═══════════════════════════════════════════════════════════════════════════
// PUBLIC HELPERS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Collect the IDs of all subtree nodes referenced in a flat node array.
 */
export function getReferencedSubtreeIds(nodes: AppNode[]): string[] {
  const seen = new Set<string>();
  for (const node of nodes) {
    if (node.data?.category === 'subtree') {
      const id = node.data.subtreeId || node.data.type;
      if (id) seen.add(id);
    }
  }
  return Array.from(seen);
}

/**
 * Patch a specific subtree inside an existing XML string.
 *
 * If the subtree already exists it is replaced in-place; otherwise a new
 * `<BehaviorTree>` element is appended before `</root>`.
 *
 * Used to efficiently propagate library changes to workspace files
 * without a full re-parse / re-serialize cycle.
 */
export function updateSubtreeInXML(
  xmlString: string,
  subtreeId: string,
  newSubtreeData: TreeData,
): string {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(xmlString, 'text/xml');
  const root = xmlDoc.querySelector('root');
  if (!root) return xmlString;

  // Locate existing element
  let targetElement: Element | null = null;
  root.querySelectorAll('BehaviorTree').forEach((bt) => {
    if (bt.getAttribute('ID') === subtreeId) {
      targetElement = bt;
    }
  });

  // Serialize the replacement content
  const structure = buildTreeStructure(newSubtreeData.nodes, newSubtreeData.edges);
  const newContent = serializeNodeRecursive(
    structure.root,
    newSubtreeData.nodes,
    newSubtreeData.edges,
    newSubtreeData.variables,
    2,
  );

  if (targetElement !== null) {
    (targetElement as Element).innerHTML = newContent;
  } else {
    const newBT = xmlDoc.createElement('BehaviorTree');
    newBT.setAttribute('ID', subtreeId);
    newBT.innerHTML = newContent;
    root.appendChild(newBT);
  }

  // Re-serialize to string and tidy up formatting artefacts
  const serializer = new XMLSerializer();
  let result = serializer.serializeToString(xmlDoc);
  result = result.replace(/><BehaviorTree/g, '>\n\n  <BehaviorTree');
  result = result.replace(/<\/BehaviorTree><\/root>/g, '</BehaviorTree>\n</root>');
  return result;
}

// ═══════════════════════════════════════════════════════════════════════════
// SERIALIZATION HELPERS (private)
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Serialize a single `<BehaviorTree>` element (description comment + color comment + body).
 */
function serializeBehaviorTree(tree: TreeData): string {
  let xml = '';

  if (tree.description) {
    xml += `  <!-- ${escapeXML(tree.description)} -->\n`;
  }

  if (tree.color) {
    xml += `  <!-- BTstudio:color=${escapeXML(tree.color)} -->\n`;
  }

  xml += `  <BehaviorTree ID="${escapeXML(tree.id)}">\n`;
  const structure = buildTreeStructure(tree.nodes, tree.edges);
  xml += serializeNodeRecursive(structure.root, tree.nodes, tree.edges, tree.variables, 2);
  xml += '  </BehaviorTree>\n';

  return xml;
}

/**
 * Build a parent -> children map and locate the root node.
 */
function buildTreeStructure(
  nodes: AppNode[],
  edges: AppEdge[],
): { root: AppNode | null; childrenMap: Map<string, string[]> } {
  const root = nodes.find((n) => n.data?.category === 'root') ?? null;

  const childrenMap = new Map<string, string[]>();
  for (const edge of edges) {
    const children = childrenMap.get(edge.source) ?? [];
    children.push(edge.target);
    childrenMap.set(edge.source, children);
  }

  // Sort children by visual x-position (left to right)
  childrenMap.forEach((children, _parentId) => {
    children.sort((a, b) => {
      const ax = nodes.find((n) => n.id === a)?.position?.x ?? 0;
      const bx = nodes.find((n) => n.id === b)?.position?.x ?? 0;
      return ax - bx;
    });
  });

  return { root, childrenMap };
}

/**
 * Recursively serialize a node and its children to BT XML.
 *
 * The root node itself is transparent -- it serializes its single child
 * directly, because BehaviorTree.cpp trees always start below `<BehaviorTree>`.
 */
function serializeNodeRecursive(
  node: AppNode | null,
  nodes: AppNode[],
  edges: AppEdge[],
  variables: Variable[],
  indentLevel: number,
): string {
  if (!node) return '';

  const indent = '  '.repeat(indentLevel);
  const { data } = node;

  // Root is transparent: serialize its single child
  if (data?.category === 'root') {
    const children = getNodeChildren(node.id, nodes, edges);
    return children.length > 0
      ? serializeNodeRecursive(children[0], nodes, edges, variables, indentLevel)
      : '';
  }

  // SubTree nodes use a dedicated format
  if (data?.category === 'subtree') {
    return serializeSubTreeNode(node, indentLevel);
  }

  // --- Regular node ---

  const nodeType = data?.type ?? 'Unknown';
  // DeclareVariable is an editor-only concept; export as SetBlackboard
  const exportType = nodeType === 'DeclareVariable' ? 'SetBlackboard' : nodeType;

  const fields: NodeField[] = data?.fields ?? [];
  const nodeName: string | undefined = data?.nodeName;

  const attrs = buildAttributeString(fields, nodeName);
  const children = getNodeChildren(node.id, nodes, edges);

  if (children.length === 0) {
    return `${indent}<${exportType}${attrs}/>\n`;
  }

  let xml = `${indent}<${exportType}${attrs}>\n`;
  for (const child of children) {
    xml += serializeNodeRecursive(child, nodes, edges, variables, indentLevel + 1);
  }
  xml += `${indent}</${exportType}>\n`;
  return xml;
}

/** Serialize a SubTree reference node (always self-closing). */
function serializeSubTreeNode(node: AppNode, indentLevel: number): string {
  const indent = '  '.repeat(indentLevel);
  const { data } = node;
  const subtreeId: string = data?.subtreeId ?? data?.type ?? 'UnnamedSubTree';
  const fields: NodeField[] = data?.fields ?? [];
  const nodeName: string | undefined = data?.nodeName;

  const attrs = buildAttributeString(fields, nodeName);
  return `${indent}<SubTree ID="${subtreeId}"${attrs}/>\n`;
}

/**
 * Build an XML attributes string from a node's fields and optional name.
 *
 * The `name` attribute is emitted first per BehaviorTree.cpp convention.
 * `output_key` values have their display braces stripped on export.
 */
function buildAttributeString(fields: NodeField[], nodeName?: string): string {
  const parts: string[] = [];

  if (nodeName) {
    parts.push(`name="${escapeXML(nodeName)}"`);
  }

  for (const field of fields) {
    let value = field.value;

    // output_key is stored with braces for display; strip them on export
    if (field.name === 'output_key' && typeof value === 'string') {
      value = value.replace(/^\{|\}$/g, '');
    }

    if (field.valueType === 'variable') {
      parts.push(`${field.name}="{${value}}"`);
    } else {
      parts.push(`${field.name}="${escapeXML(String(value))}"`);
    }
  }

  return parts.length > 0 ? ' ' + parts.join(' ') : '';
}

/**
 * Get the direct children of a node, sorted left-to-right by x-position.
 */
function getNodeChildren(nodeId: string, nodes: AppNode[], edges: AppEdge[]): AppNode[] {
  const childIds = edges.filter((e) => e.source === nodeId).map((e) => e.target);
  return childIds
    .map((id) => nodes.find((n) => n.id === id))
    .filter((n): n is AppNode => n !== undefined)
    .sort((a, b) => (a.position?.x ?? 0) - (b.position?.x ?? 0));
}

/**
 * Serialize the `<TreeNodesModel>` section that declares subtree port interfaces.
 */
function serializeTreeNodesModel(subtrees: Map<string, TreeData>): string {
  const withPorts: TreeData[] = [];
  subtrees.forEach((td) => {
    if (td.ports && td.ports.length > 0) withPorts.push(td);
  });
  if (withPorts.length === 0) return '';

  let xml = '  <!-- Subtree port definitions -->\n';
  xml += '  <TreeNodesModel>\n';

  for (const tree of withPorts) {
    xml += `    <SubTree ID="${escapeXML(tree.id)}">\n`;
    for (const port of tree.ports!) {
      const tag =
        port.direction === 'input' ? 'input_port' :
        port.direction === 'output' ? 'output_port' : 'inout_port';
      const defaultAttr = port.defaultValue ? ` default="${escapeXML(port.defaultValue)}"` : '';
      const typeAttr = port.type ? ` type="${port.type}"` : '';
      const reqAttr = port.required ? ' required="true"' : '';
      const desc = port.description ? escapeXML(port.description) : '';
      xml += `      <${tag} name="${escapeXML(port.name)}"${typeAttr}${defaultAttr}${reqAttr}>${desc}</${tag}>\n`;
    }
    xml += '    </SubTree>\n';
  }

  xml += '  </TreeNodesModel>\n\n';
  return xml;
}

// ═══════════════════════════════════════════════════════════════════════════
// PARSING HELPERS (private)
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Parse an XML string, validate it, and return the `<root>` element.
 */
function parseAndValidateRoot(xmlString: string): Element {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(xmlString, 'text/xml');

  const parseError = xmlDoc.querySelector('parsererror');
  if (parseError) {
    throw new Error('Invalid XML: ' + parseError.textContent);
  }

  const root = xmlDoc.querySelector('root');
  if (!root) {
    throw new Error('Invalid BehaviorTree XML: missing root element');
  }
  return root;
}

/**
 * Walk the children of `<root>` and map each `<BehaviorTree>` to the
 * preceding XML comments (if any), extracting description and BTstudio metadata.
 *
 * This is used to recover subtree descriptions and custom colors that are
 * stored as XML comments rather than attributes.
 */
function buildDescriptionMap(root: Element): Map<string, string> {
  const map = new Map<string, string>();
  let currentDescription: string | null = null;

  // nodeType 8 = COMMENT_NODE, 1 = ELEMENT_NODE
  root.childNodes.forEach((child) => {
    if (child.nodeType === 8) {
      const text = (child.textContent ?? '').trim();
      // Only track user description comments (skip generated and BTstudio meta)
      if (!isGeneratedComment(text) && !isBTstudioMetaComment(text)) {
        currentDescription = text;
      }
    } else if (child.nodeType === 1 && (child as Element).tagName === 'BehaviorTree') {
      const treeId = (child as Element).getAttribute('ID');
      if (treeId && currentDescription) {
        map.set(treeId, currentDescription);
      }
      currentDescription = null;
    } else if (child.nodeType === 1) {
      currentDescription = null;
    }
  });

  return map;
}

/**
 * Walk the children of `<root>` and extract BTstudio metadata comments
 * (e.g., `BTstudio:color=#FF5722`) preceding each `<BehaviorTree>` element.
 *
 * Returns a map from tree ID to color hex string.
 */
function buildColorMap(root: Element): Map<string, string> {
  const map = new Map<string, string>();
  const pendingColors: string[] = [];

  root.childNodes.forEach((child) => {
    if (child.nodeType === 8) {
      const text = (child.textContent ?? '').trim();
      const colorMatch = text.match(/^BTstudio:color=(.+)$/);
      if (colorMatch) {
        pendingColors.push(colorMatch[1]);
      }
    } else if (child.nodeType === 1 && (child as Element).tagName === 'BehaviorTree') {
      const treeId = (child as Element).getAttribute('ID');
      if (treeId && pendingColors.length > 0) {
        map.set(treeId, pendingColors[pendingColors.length - 1]);
      }
      pendingColors.length = 0;
    } else if (child.nodeType === 1) {
      pendingColors.length = 0;
    }
  });

  return map;
}

/** Returns true for comments generated by BTstudio that are NOT user descriptions. */
function isGeneratedComment(text: string): boolean {
  const lower = text.toLowerCase();
  return (
    lower.includes('generated by') ||
    lower.includes('subtree library') ||
    lower.includes('port definitions')
  );
}

/** Returns true for BTstudio metadata comments (e.g., color). */
function isBTstudioMetaComment(text: string): boolean {
  return text.startsWith('BTstudio:');
}

/**
 * Parse a single `<BehaviorTree>` element into a TreeData object.
 */
function parseBehaviorTreeElement(
  btElement: Element,
  treeId: string,
  description: string | undefined,
  color: string | undefined,
): TreeData {
  const variables: Variable[] = [];
  const firstSetBlackboardPerVariable = new Map<string, Element>();

  // Scan for SetBlackboard nodes to identify variable declarations
  collectSetBlackboardNodes(btElement, firstSetBlackboardPerVariable);

  const { nodes, edges } = parseTreeStructure(btElement, variables, firstSetBlackboardPerVariable);
  return { id: treeId, nodes, edges, variables, description, color };
}

/**
 * Recursively collect the first SetBlackboard element for each output_key.
 * The first occurrence is treated as a variable declaration.
 */
function collectSetBlackboardNodes(element: Element, map: Map<string, Element>): void {
  if (element.tagName === 'SetBlackboard') {
    const key = element.getAttribute('output_key');
    if (key && !map.has(key)) {
      map.set(key, element);
    }
  }
  for (const child of Array.from(element.children)) {
    collectSetBlackboardNodes(child, map);
  }
}

/**
 * Parse the children of a `<BehaviorTree>` element into ReactFlow nodes and edges.
 *
 * Always creates a synthetic Root node at the top of the tree.
 */
function parseTreeStructure(
  btElement: Element,
  variables: Variable[],
  firstSetBlackboardPerVariable: Map<string, Element>,
): { nodes: AppNode[]; edges: AppEdge[] } {
  const nodes: AppNode[] = [];
  const edges: AppEdge[] = [];

  // Synthetic root node
  const rootNode: AppNode = {
    id: 'root_node',
    type: 'btNode',
    position: { x: 250, y: 50 },
    data: {
      id: 'root',
      type: 'Root',
      category: 'root',
      name: 'Root',
      description: 'Root node of the behavior tree',
      fields: [],
      instanceId: 'root_node',
      color: getCategoryColor('root'),
    },
  };
  nodes.push(rootNode);

  const firstChild = btElement.children[0];
  if (firstChild) {
    const result = parseNodeRecursive(
      firstChild,
      250, // xPosition
      150, // yPosition
      0,   // depth
      variables,
      firstSetBlackboardPerVariable,
    );

    if (result.node) {
      nodes.push(result.node);
      // Add descendant nodes (skip the duplicate root already added)
      nodes.push(...result.allNodes.filter((n) => n.id !== result.node!.id));
      edges.push({
        id: `root_node-${result.node.id}`,
        source: 'root_node',
        target: result.node.id,
      });
      edges.push(...result.edges);
    }
  }

  return { nodes, edges };
}

/**
 * Recursively parse an XML element into a ReactFlow node and its descendant tree.
 */
function parseNodeRecursive(
  element: Element,
  x: number,
  y: number,
  depth: number,
  variables: Variable[],
  firstSetBlackboardPerVariable: Map<string, Element>,
): {
  node: AppNode | null;
  edges: AppEdge[];
  allNodes: AppNode[];
} {
  const edges: AppEdge[] = [];
  const allNodes: AppNode[] = [];
  let nodeType = element.tagName;

  // SubTree nodes have their own parsing path
  if (nodeType === 'SubTree') {
    const subtreeId = element.getAttribute('ID') || 'UnnamedSubTree';
    const node = createSubTreeNode(element, subtreeId, x, y);
    return { node, edges, allNodes: [node] };
  }

  // Detect DeclareVariable (first SetBlackboard per output_key)
  let isDeclareVariable = false;
  if (nodeType === 'SetBlackboard') {
    const outputKey = element.getAttribute('output_key');
    if (outputKey && firstSetBlackboardPerVariable.get(outputKey) === element) {
      isDeclareVariable = true;
      nodeType = 'DeclareVariable';
      variables.push({ name: outputKey, value: element.getAttribute('value') ?? '' });
    }
  }

  const nodeId = `${nodeType}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  const category = inferCategoryFromType(isDeclareVariable ? 'SetBlackboard' : nodeType);
  const nodeName = element.getAttribute('name') || undefined;

  // Parse XML attributes into NodeField[]
  const fields = parseElementAttributes(element, nodeType);

  const node: AppNode = {
    id: nodeId,
    type: 'btNode',
    position: { x, y },
    data: {
      id: nodeType.toLowerCase(),
      type: nodeType,
      category,
      name: isDeclareVariable ? 'Declare Variable' : nodeType,
      description: isDeclareVariable
        ? 'Declares a variable with an initial value (first assignment)'
        : `${nodeType} node`,
      fields,
      nodeName,
      instanceId: nodeId,
      color: getCategoryColor(category),
    },
  };
  allNodes.push(node);

  // Recursively parse children
  const children = Array.from(element.children);
  const childSpacing = 200;
  const totalWidth = children.length * childSpacing;
  let childX = x - totalWidth / 2 + childSpacing / 2;
  const childY = y + 100;

  for (const child of children) {
    const result = parseNodeRecursive(child, childX, childY, depth + 1, variables, firstSetBlackboardPerVariable);
    if (result.node) {
      edges.push({
        id: `${nodeId}-${result.node.id}`,
        source: nodeId,
        target: result.node.id,
      });
      allNodes.push(...result.allNodes);
      edges.push(...result.edges);
    }
    childX += childSpacing;
  }

  return { node, edges, allNodes };
}

/**
 * Parse XML attributes of an element into a NodeField array.
 *
 * Skips the `ID` and `name` attributes (handled separately).
 * Detects `{varName}` references and auto-parses numbers / booleans.
 */
function parseElementAttributes(element: Element, nodeType: string): NodeField[] {
  const fields: NodeField[] = [];
  const isBlackboardType = nodeType === 'SetBlackboard' || nodeType === 'DeclareVariable';

  for (const attr of Array.from(element.attributes)) {
    if (attr.name === 'ID' || attr.name === 'name') continue;

    const raw = attr.value;
    let valueType: NodeField['valueType'] = 'literal';
    let parsedValue: string | number | boolean = raw;

    // Detect {varName} references
    const varMatch = raw.match(/^\{(.+)\}$/);
    if (varMatch) {
      valueType = 'variable';
      parsedValue = varMatch[1];
    } else if (!isNaN(Number(raw))) {
      parsedValue = Number(raw);
    } else if (raw === 'true' || raw === 'false') {
      parsedValue = raw === 'true';
    }

    // output_key for blackboard nodes gets display braces
    const displayValue =
      attr.name === 'output_key' && isBlackboardType
        ? `{${parsedValue}}`
        : parsedValue;

    fields.push({
      name: attr.name,
      type: typeof parsedValue === 'number' ? 'number' : typeof parsedValue === 'boolean' ? 'boolean' : 'string',
      valueType,
      value: displayValue,
    });
  }

  return fields;
}

/** Create a SubTree reference node from an XML element. */
function createSubTreeNode(element: Element, subtreeId: string, x: number, y: number): AppNode {
  const nodeId = `SubTree_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  const nodeName = element.getAttribute('name') || undefined;

  // Port mappings come from XML attributes (excluding ID and name)
  const fields = parseElementAttributes(element, 'SubTree');

  return {
    id: nodeId,
    type: 'btNode',
    position: { x, y },
    data: {
      id: subtreeId.toLowerCase(),
      type: subtreeId,
      category: 'subtree',
      name: subtreeId,
      description: `SubTree: ${subtreeId}`,
      fields,
      subtreeId,
      nodeName,
      instanceId: nodeId,
      color: getCategoryColor('subtree'),
    },
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// PORT DEFINITION PARSING
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Parse `<TreeNodesModel>` and attach port definitions to matching subtrees.
 */
function attachPortDefinitions(root: Element, subtrees: Map<string, TreeData>): void {
  const portDefs = parseTreeNodesModel(root);
  portDefs.forEach((ports, id) => {
    const subtree = subtrees.get(id);
    if (subtree) subtree.ports = ports;
  });
}

/**
 * Walk all trees and annotate SubTree reference nodes' fields with
 * `portDirection` from the port definitions in `<TreeNodesModel>` or
 * from the referenced subtree's TreeData.
 *
 * This ensures that after XML import, subtree instances display the
 * correct [IN]/[OUT] port labels in the editor.
 */
function annotateSubTreeNodeFields(
  trees: TreeData[],
  portDefinitions: Map<string, SubTreePort[]>,
  subtreeDataMap: Map<string, TreeData>,
): void {
  for (const tree of trees) {
    for (const node of tree.nodes) {
      if (node.data?.category !== 'subtree') continue;

      const subtreeId = node.data.subtreeId || node.data.type;
      if (!subtreeId) continue;

      // Resolve ports from TreeNodesModel first, then from subtree TreeData
      const ports =
        portDefinitions.get(subtreeId) ??
        subtreeDataMap.get(subtreeId)?.ports;
      if (!ports || ports.length === 0) continue;

      // Build a port-name -> direction map
      const portDirMap = new Map<string, 'input' | 'output'>();
      for (const port of ports) {
        // 'inout' ports are treated as input for display purposes
        portDirMap.set(port.name, port.direction === 'output' ? 'output' : 'input');
      }

      // Annotate existing fields with portDirection
      node.data.fields = node.data.fields.map(field => {
        const dir = portDirMap.get(field.name);
        if (dir) return { ...field, portDirection: dir };
        return field;
      });

      // Attach ports to the node data for UI consistency
      node.data.ports = ports;
    }
  }
}

/**
 * Parse the `<TreeNodesModel>` section for subtree port definitions.
 */
function parseTreeNodesModel(root: Element): Map<string, SubTreePort[]> {
  const result = new Map<string, SubTreePort[]>();
  const model = root.querySelector('TreeNodesModel');
  if (!model) return result;

  for (const subtreeModel of Array.from(model.querySelectorAll('SubTree'))) {
    const subtreeId = subtreeModel.getAttribute('ID');
    if (!subtreeId) continue;

    const ports: SubTreePort[] = [
      ...parsePortElements(subtreeModel, 'input_port', 'input'),
      ...parsePortElements(subtreeModel, 'output_port', 'output'),
      ...parsePortElements(subtreeModel, 'inout_port', 'inout'),
    ];

    if (ports.length > 0) {
      result.set(subtreeId, ports);
    }
  }

  return result;
}

/**
 * Parse all port elements of a given tag name within a parent element.
 *
 * Shared by input_port, output_port, and inout_port parsing to avoid
 * duplicating the same attribute-extraction logic three times.
 */
function parsePortElements(
  parent: Element,
  tagName: string,
  direction: SubTreePort['direction'],
): SubTreePort[] {
  const ports: SubTreePort[] = [];

  for (const el of Array.from(parent.querySelectorAll(tagName))) {
    const name = el.getAttribute('name');
    if (!name) continue;

    ports.push({
      name,
      direction,
      type: (el.getAttribute('type') as SubTreePort['type']) || 'string',
      defaultValue: el.getAttribute('default') || undefined,
      description: el.textContent || undefined,
      required: el.getAttribute('required') === 'true',
    });
  }

  return ports;
}

// ═══════════════════════════════════════════════════════════════════════════
// XML UTILITIES
// ═══════════════════════════════════════════════════════════════════════════

/** Escape the five special XML characters. */
function escapeXML(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
